config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  post '/signup', to: 'users#create'
  get '/me', to: 'users#show'

  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :blogs, only: [:index, :show, :create, :update, :destroy] do
    resources :comments, only: [:create, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy

    validates :title, presence: true
    validates :content, presence: true, length: { minimum: 10 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :blog

  validates :content, presence: true, length: { minimum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
    has_many :blogs, dependent: :destroy
    has_many :comments
    has_secure_password

    validates :username, presence: true, uniqueness: true
    validates :email, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    skip_before_action :verify_authenticity_token
    # protect_from_forgery 

    before_action :logged_in?

    private

    def logged_in?
        unless session.include? :current_user_id
            render json: { error: "Please log in."}, status: :unauthorized 
        end
    end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
    before_action :set_blog, only: [:show, :update, :destroy]

    rescue_from ActiveRecord::RecordNotFound, with: :render_record_not_found
    rescue_from ActiveRecord::RecordInvalid, with: :render_record_invalid

    def index
        blogs = Blog.all

        render json: { blogs: blogs }, status: :created
    end

    def show
        blog = Blog.find(params[:id])

        render json: { user: blog.user, blog: blog }, status: :created
    end

    def create
        blog = Blog.create!(blog_params)

        if blog
            render json: { user: blog.user, blog: blog }, status: :created
        else
            render json: { errors: blog.errors.full_messages }, status: :unprocessable_entity
        end
    end

    def update
        blog = Blog.find(params[:id])

        if blog.update(blog_params)
            render json: { user: blog.user, blog: blog }, status: :created
        else
            render json: { errors: blog.errors.full_messages }, status: :unprocessable_entity
        end
    end

    def destroy
        blog = Blog.find(params[:id])
        blog.destroy

        render json: { success: "Blog destroyed."}, status: :see_other
    end

    private

    def set_blog
        blog = Blog.find(params[:id])
    end

    def set_user
        user = User.find_by(id: session[:current_user_id])
    end

    def blog_params
        user = set_user
        user_id = user.id

        params
        .require(:blog)
        .permit(:user_id, :title, :description, :content)
        .merge(user_id: user_id)
    end

    def render_record_not_found
        render json: { status: "Record Not Found." }
    end

    def render_record_invalid
        render json: { status: "Record Invalid." }
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :set_blog

    def create
        comment = blog.comments.create!(comment_params)

        if comment
            render json: { comment: comment}, status: :created
        else
            render json: { errors: comment.errors.full_messages }, status: :unprocessable_entity
        end
    end

    def destroy
        comment = blog.comments.find(params[:id])
        comment.destroy

        render json: { success: "Comment destroyed."}, status: :see_other
    end

    private

    def set_blog
        blog = Blog.find(params[:blog_id])
    end

    def comment_params
        params.require(:comment).permit(:content)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    skip_before_action :logged_in?, only: [:create]

    def create
        if params[:username]
            user = User.find_by(username: params[:username])
        else
            user = User.find_by(email: params[:email])
        end

        if user&.authenticate(params[:password])
            session[:current_user_id] = user.id

            render json: { 
                logged_in: true, 
                user: user,
                blogs: user.blogs,
                comments: user.comments 
            }, 
                status: :created
        else
            render json: { errors: user.errors.full_messages }, status: :unprocessable_entity
        end

    end

    def destroy
        session.delete :current_user_id

        render json: { success: "Session deleted."}
    end

    private

    def session_params
        params.require(:user).permit(:username, :email, :password)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :logged_in?, only: [:create]

    def create
        user = User.create!(user_params)

        if user
            session[:current_user_id] = user.id

            render json: { user: user }, status: :created
        else
            render json: { errors: user.errors.full_messages }, status: :unprocessable_entity
        end

    end

    def show
        user = User.find_by(id: session[:current_user_id])

        render json: { user: user, blogs: user.blogs }, status: :created
    end

    private

    def user_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_with model: blog do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% blog.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :content %><br>
    <%= form.text_area :content %><br>
    <% blog.errors.full_messages_for(:content).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Edit Blog</h1>

<%= render "form", blog: @blog %>
<%= link_to "Back", blogs_path %>

app/views/blogs/index.html.erb
<h1>Blogs</h1>

<ul>
    <% @blogs.each do |blog| %>
        <li>
            <a href="<%= blog_path(blog) %>">
                <h3>#<%= blog.id %>   <%= blog.title %></h3>
            </a>
            <h4><%= blog.content %></h4>
        </li>
    <% end %>
</ul>

<h3>
    <%= link_to "New Blog", new_blog_path %>
</h3>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render "form", blog: @blog %>
<%= link_to "Back", blogs_path %>

app/views/blogs/show.html.erb
<h1>#<%= @blog.id %>   <%= @blog.title %></h1>
<p><%= @blog.content %></p>

<ul>
  <li><%= link_to "Edit", edit_blog_path(@blog) %></li>
  <li>
    <%= link_to "Destroy", blog_path(@blog), method: "delete", data: { confirm: "Are you sure?", disable_with: "Processing..." } %>
  </li>
</ul>

<h2>Comments</h2>
<% @blog.comments.each do |comment| %>
  <p>
    <strong>---</strong>
    <%= comment.content %>
  </p>
  <p>
    <%= link_to "Destroy Comment", [comment.blog, comment], method: "delete", data: { confirm: "Are you sure?", disable_with: "Processing..." } %>
  </p>
<% end %>

<h2>Add a comment:</h2>
<%= form_with model: [ @blog, @blog.comments.build ] do |form| %>
  <p>
    <%= form.label :content %><br>
    <%= form.text_area :content %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to "Blog List", blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>